version: "3.8"
services:
  my-gateway-demo5:
    image: my-gateway-demo5:latest
    build: .
    container_name: my-gateway-demo5
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/app/config
    ports:
      - 20238:8083
    restart: unless-stopped
